/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package display;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author nhanDT
 */
public class About extends javax.swing.JFrame {
    Image appLogo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img2/Logo.png"));
    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 
        pnlAbout.setOpaque(false);
        setIconImage(appLogo);
        this.setResizable(false);
        lblBack.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlAbout = new javax.swing.JPanel();
        lblAbout = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblDesign = new javax.swing.JLabel();
        lblDeveloped = new javax.swing.JLabel();
        lblLeader1 = new javax.swing.JLabel();
        lblLeader2 = new javax.swing.JLabel();
        lblPlecial = new javax.swing.JLabel();
        lblMentor = new javax.swing.JLabel();
        lblThis = new javax.swing.JLabel();
        lblAboutBR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlAbout.setPreferredSize(new java.awt.Dimension(700, 426));

        lblAbout.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(153, 153, 255));
        lblAbout.setText("About");

        lblBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Back");
        lblBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        lblDesign.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDesign.setForeground(new java.awt.Color(204, 204, 255));
        lblDesign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesign.setText("Design");

        lblDeveloped.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDeveloped.setForeground(new java.awt.Color(204, 204, 255));
        lblDeveloped.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeveloped.setText("Developed By DTN-Group");

        lblLeader1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLeader1.setForeground(new java.awt.Color(255, 255, 255));
        lblLeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeader1.setText("Leader: Duong Trong Nhan");

        lblLeader2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLeader2.setForeground(new java.awt.Color(255, 255, 255));
        lblLeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeader2.setText("Leader: Duong Trong Nhan");

        lblPlecial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPlecial.setForeground(new java.awt.Color(204, 204, 255));
        lblPlecial.setText("Special thanks to");

        lblMentor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMentor.setForeground(new java.awt.Color(255, 255, 255));
        lblMentor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMentor.setText("Mentor: Vo Hong Khanh ");

        lblThis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblThis.setForeground(new java.awt.Color(255, 255, 255));
        lblThis.setText("This game would not have been developed without yours guidance");

        javax.swing.GroupLayout pnlAboutLayout = new javax.swing.GroupLayout(pnlAbout);
        pnlAbout.setLayout(pnlAboutLayout);
        pnlAboutLayout.setHorizontalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutLayout.createSequentialGroup()
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblLeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(lblLeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblAbout)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lblPlecial))
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lblMentor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblThis)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lblDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDeveloped)
                .addGap(59, 59, 59))
        );
        pnlAboutLayout.setVerticalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblAbout))
                    .addGroup(pnlAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDeveloped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeader2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(lblPlecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMentor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThis)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(pnlAbout, gridBagConstraints);

        lblAboutBR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nenGameAilatrieuphuAboutHelp.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblAboutBR, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * close jframe
 * @param evt 
 */
    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_lblBackMouseClicked

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAboutBR;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblDesign;
    private javax.swing.JLabel lblDeveloped;
    private javax.swing.JLabel lblLeader1;
    private javax.swing.JLabel lblLeader2;
    private javax.swing.JLabel lblMentor;
    private javax.swing.JLabel lblPlecial;
    private javax.swing.JLabel lblThis;
    private javax.swing.JPanel pnlAbout;
    // End of variables declaration//GEN-END:variables
}
