/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package display;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author nhanDT
 */
public class Help extends javax.swing.JFrame {

    private int number = 1;
    Image appLogo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img2/Logo.png"));
    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 
        pnlHelp.setOpaque(false);
        lblImgHelp.setIcon(new ImageIcon(getClass().getResource("/imgHelp/Help" + number+".png")));
        setIconImage(appLogo);
        this.setResizable(false);
        lblBack.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHelp = new javax.swing.JPanel();
        lblHelp = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblImgHelp = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        lblHelpBR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Help");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblHelp.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(153, 153, 255));
        lblHelp.setText("Help");

        lblBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Back");
        lblBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        lblImgHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgHelp/Help1.png"))); // NOI18N

        lblRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgHelp/forwardArrow.png"))); // NOI18N
        lblRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRightMouseClicked(evt);
            }
        });

        lblLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgHelp/backArrow.png"))); // NOI18N
        lblLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeftMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlHelpLayout = new javax.swing.GroupLayout(pnlHelp);
        pnlHelp.setLayout(pnlHelpLayout);
        pnlHelpLayout.setHorizontalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(lblHelp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHelpLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblImgHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblRight)
                .addGap(38, 38, 38))
        );
        pnlHelpLayout.setVerticalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpLayout.createSequentialGroup()
                .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHelpLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblHelp))
                    .addGroup(pnlHelpLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHelpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImgHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHelpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLeft)
                        .addGap(157, 157, 157))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHelpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRight)
                .addGap(164, 164, 164))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(pnlHelp, gridBagConstraints);

        lblHelpBR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nenGameAilatrieuphuAboutHelp.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblHelpBR, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * close jframe
 * @param evt 
 */
    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_lblBackMouseClicked
/**
 * back img
 * @param evt 
 */
    private void lblLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeftMouseClicked
        if (number>1) {
            number--;
            lblImgHelp.setIcon(new ImageIcon(getClass().getResource("/imgHelp/Help" + number+".png")));
        }
        
    }//GEN-LAST:event_lblLeftMouseClicked
/**
 * forward img
 * @param evt 
 */
    private void lblRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRightMouseClicked
        if (number < 9) {
            number++;
            lblImgHelp.setIcon(new ImageIcon(getClass().getResource("/imgHelp/Help" + number+".png")));
        }

    }//GEN-LAST:event_lblRightMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblHelpBR;
    private javax.swing.JLabel lblImgHelp;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblRight;
    private javax.swing.JPanel pnlHelp;
    // End of variables declaration//GEN-END:variables
}
