/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package display;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import whowantstobeamillionaire_game.UserModel;

/**
 *
 * @author nhanDT
 */
public class Leaderboard extends javax.swing.JFrame {
    Image appLogo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img2/Logo.png"));

    /**
     * Creates new form Leaderboard
     */
    public Leaderboard() throws SQLException, IOException {
        initComponents();
        this.setResizable(false);
        setIconImage(appLogo);
        pnlBRLeaderboard.setOpaque(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        load();
        lblBack.setOpaque(true);
    }
/**
 * load database
 * @throws IOException
 * @throws SQLException 
 */
    public void load() throws IOException, SQLException {
        UserModel um = new UserModel();
        um.LoadUser();
        DefaultTableModel model = (DefaultTableModel) tblLeaderboard.getModel();
        //store row data
        Object rowData[] = new Object[3];
        int a = um.getListPlayer().size();
        System.out.println(a);
        for (int i = 0; i < a; i++) {
            rowData[0] = i + 1;
            rowData[1] = um.getListPlayer().get(i).getName_user();
            rowData[2] = um.getListPlayer().get(i).getPoint_user()+"$";
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBRLeaderboard = new javax.swing.JPanel();
        lblLeaderboard = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        splLeaderboard = new javax.swing.JScrollPane();
        tblLeaderboard = new javax.swing.JTable();
        lblBRLeaderboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leaderboard");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblLeaderboard.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLeaderboard.setForeground(new java.awt.Color(153, 153, 255));
        lblLeaderboard.setText("Leaderboard");

        lblBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("Back");
        lblBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        tblLeaderboard.setBackground(new java.awt.Color(0, 0, 204));
        tblLeaderboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblLeaderboard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblLeaderboard.setForeground(new java.awt.Color(204, 255, 255));
        tblLeaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Name", "Money"
            }
        ));
        tblLeaderboard.setEditingRow(20);
        tblLeaderboard.setSelectionForeground(new java.awt.Color(0, 153, 255));
        splLeaderboard.setViewportView(tblLeaderboard);
        tblLeaderboard.getAccessibleContext().setAccessibleName("");
        tblLeaderboard.getAccessibleContext().setAccessibleParent(tblLeaderboard);

        javax.swing.GroupLayout pnlBRLeaderboardLayout = new javax.swing.GroupLayout(pnlBRLeaderboard);
        pnlBRLeaderboard.setLayout(pnlBRLeaderboardLayout);
        pnlBRLeaderboardLayout.setHorizontalGroup(
            pnlBRLeaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBRLeaderboardLayout.createSequentialGroup()
                .addGroup(pnlBRLeaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBRLeaderboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(lblLeaderboard))
                    .addGroup(pnlBRLeaderboardLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(splLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pnlBRLeaderboardLayout.setVerticalGroup(
            pnlBRLeaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBRLeaderboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBRLeaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLeaderboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(splLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(pnlBRLeaderboard, gridBagConstraints);

        lblBRLeaderboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nenGameAilatrieuphuAboutHelp.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblBRLeaderboard, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * close jframe
 * @param evt 
 */
    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_lblBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBRLeaderboard;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JPanel pnlBRLeaderboard;
    private javax.swing.JScrollPane splLeaderboard;
    private javax.swing.JTable tblLeaderboard;
    // End of variables declaration//GEN-END:variables
}
