/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package display;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nhanDT
 */
public class MillionaireMenu extends javax.swing.JFrame {

    String userName = "Player";
    Image appLogo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img2/Logo.png"));
    /**
     * Creates new form MillionaireGame
     */
    public MillionaireMenu() throws SQLException {
        initComponents();
        pnlGame.setOpaque(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); 
        dlLogin.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        lblPlaygame.setOpaque(true);
        lblLeaderboard.setOpaque(true);
        lblHelp.setOpaque(true);
        lblAbout.setOpaque(true);
        lblExit.setOpaque(true);
        dlLogin.setSize(420, 240);
        dlLogin.setLocationRelativeTo(null);
        this.setIconImage(appLogo);
        dlLogin.setIconImage(appLogo);
        this.setResizable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dlLogin = new javax.swing.JDialog();
        lblOKPlayer = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        tfdUserName = new javax.swing.JTextField();
        lblBRLogin = new javax.swing.JLabel();
        pnlGame = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblPlaygame = new javax.swing.JLabel();
        lblLeaderboard = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        dlLogin.setTitle("Login Player");
        dlLogin.getContentPane().setLayout(null);

        lblOKPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/OK.png"))); // NOI18N
        lblOKPlayer.setText("jLabel1");
        lblOKPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOKPlayerMouseClicked(evt);
            }
        });
        dlLogin.getContentPane().add(lblOKPlayer);
        lblOKPlayer.setBounds(150, 140, 100, 40);

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("User Name:");
        dlLogin.getContentPane().add(lblUsername);
        lblUsername.setBounds(10, 70, 110, 22);
        dlLogin.getContentPane().add(tfdUserName);
        tfdUserName.setBounds(120, 60, 260, 30);

        lblBRLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nenGameAilatrieuphuAboutHelp.jpg"))); // NOI18N
        lblBRLogin.setText("jLabel2");
        dlLogin.getContentPane().add(lblBRLogin);
        lblBRLogin.setBounds(0, 0, 400, 200);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Millionaire Game");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoAilatrieuphu.png"))); // NOI18N

        lblPlaygame.setBackground(new java.awt.Color(102, 102, 255));
        lblPlaygame.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlaygame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlaygame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Playgame.png"))); // NOI18N
        lblPlaygame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlaygameMouseClicked(evt);
            }
        });

        lblLeaderboard.setBackground(new java.awt.Color(102, 102, 255));
        lblLeaderboard.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLeaderboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Leaderboard.png"))); // NOI18N
        lblLeaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeaderboardMouseClicked(evt);
            }
        });

        lblHelp.setBackground(new java.awt.Color(102, 102, 255));
        lblHelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Help.png"))); // NOI18N
        lblHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHelpMouseClicked(evt);
            }
        });

        lblAbout.setBackground(new java.awt.Color(102, 102, 255));
        lblAbout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/About.png"))); // NOI18N
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutMouseClicked(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(102, 102, 255));
        lblExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Exit.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblPlayer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlayer.setForeground(new java.awt.Color(255, 255, 255));
        lblPlayer.setText("Player 1");
        lblPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPlayerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlGameLayout = new javax.swing.GroupLayout(pnlGame);
        pnlGame.setLayout(pnlGameLayout);
        pnlGameLayout.setHorizontalGroup(
            pnlGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameLayout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(lblLogo)
                .addContainerGap(401, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameLayout.createSequentialGroup()
                        .addGroup(pnlGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExit)
                            .addComponent(lblAbout)
                            .addComponent(lblHelp)
                            .addComponent(lblLeaderboard)
                            .addComponent(lblPlaygame))
                        .addGap(446, 446, 446))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameLayout.createSequentialGroup()
                        .addComponent(lblPlayer)
                        .addGap(53, 53, 53))))
        );
        pnlGameLayout.setVerticalGroup(
            pnlGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblPlayer)
                .addGap(27, 27, 27)
                .addComponent(lblLogo)
                .addGap(26, 26, 26)
                .addComponent(lblPlaygame, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(pnlGame, gridBagConstraints);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nenGameAilatrieuphu.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(lblBackground, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * show frame about
 * @param evt 
 */
    private void lblAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_lblAboutMouseClicked
/**
 * show frame help
 * @param evt 
 */
    private void lblHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHelpMouseClicked
        new Help().setVisible(true);
    }//GEN-LAST:event_lblHelpMouseClicked
/**
 * show login
 * @param evt 
 */
    private void lblPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlayerMouseClicked
        dlLogin.setModal(true);
        dlLogin.setVisible(true);

    }//GEN-LAST:event_lblPlayerMouseClicked
/**
 * exit game
 * @param evt 
 */
    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked
/**
 * show play game
 * @param evt 
 */
    private void lblPlaygameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPlaygameMouseClicked

        try {
            new MillionaireGame(userName).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MillionaireMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_lblPlaygameMouseClicked
/**
 * close login and save name in database
 * @param evt 
 */
    private void lblOKPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOKPlayerMouseClicked
        userName = tfdUserName.getText();
        if (userName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "The user name must not be empty");
        } else {
            dlLogin.setVisible(false);
            
            lblPlayer.setText(userName);
            
        }
    }//GEN-LAST:event_lblOKPlayerMouseClicked
/**
 * show leaderboard
 * @param evt 
 */
    private void lblLeaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeaderboardMouseClicked
        try {
            new Leaderboard().setVisible(true);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(MillionaireMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLeaderboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MillionaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MillionaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MillionaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MillionaireMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MillionaireMenu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MillionaireMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog dlLogin;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblBRLogin;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblOKPlayer;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlaygame;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlGame;
    private javax.swing.JTextField tfdUserName;
    // End of variables declaration//GEN-END:variables
}
